[colors.bright]
black      =  "0x69605f"
blue       =  "0x89ad9f"
cyan       =  "0x41deec"
green      =  "0xc0c328"
magenta    =  "0xdb8ba1"
red        =  "0xfd513c"
white      =  "0xffffce"
yellow     =  "0xfcc138"

[colors.normal]
black      =  "0x2a2a2a"
blue       =  "0x076c7f"
cyan       =  "0x00adb6"
green      =  "0x7d780e"
magenta    =  "0x964277"
red        =  "0xe4412f"
white      =  "0xfef6c8"
yellow     =  "0xbd7b15"

[colors.primary]
background =  "0x2a2a2a"
foreground =  "0xfef6cb"
