[general]
import = ["~/.config/alacritty/theme-mine.toml",
          "~/.config/alacritty/font-jetbrains.toml",
          "~/.config/alacritty/window.toml",
          "~/.config/alacritty/mouse.toml"]

live_config_reload = false

[font]
size = 11.5
