import = ["~/.config/alacritty/theme-darktooth.toml",
          "~/.config/alacritty/font-liberation.toml",
          "~/.config/alacritty/window.toml",
          "~/.config/alacritty/mouse.toml"]

live_config_reload = false

[font]
size = 10
